import os
import json
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

model = genai.GenerativeModel('gemini-flash-latest')

SYSTEM_PROMPT = """
You are a World-Class Data Scientist Agent. 
Input: You will receive a CSV schema, data types, and a sample of the data, along with a user's analysis goal.
Task: Analyze the data and provide a comprehensive response.

Your response MUST be a single, valid JSON object with the following structure:
{
  "narrative_summary": "An executive summary of hallazgos in English.",
  "structured_data": [
    { "label": "Dimension1", "value": 10, "group": "GroupA" },
    ...
  ],
  "python_code": "Complete Python code to replicate this analysis using pandas and matplotlib/seaborn (as string).",
  "notebook_cells": [
    { "type": "markdown", "content": "# Analysis Title\\nDetailed description..." },
    { "type": "code", "content": "import pandas as pd\\n..." }
  ]
}

CRITICAL RULES:
1. ONLY return the JSON. No markdown blocks, no extra text.
2. Ensure 'structured_data' is formatted for easy consumption by Recharts (arrays of objects with labels and values).
3. The 'narrative_summary' should be insightful and professional.
4. The 'notebook_cells' should tell a story from data loading to final visualization.
"""

async def analyze_data(metadata: dict, user_prompt: str):
    api_key = os.getenv("GEMINI_API_KEY")
    
    if not api_key or api_key == "your_api_key_here":
        print("Warning: GEMINI_API_KEY missing. Returning mock analysis for UI demonstration.")
        return {
            "narrative_summary": "This is a MOCK analysis. The dataset contains multiple columns including performance metrics. A clear correlation is observed between play frequency and score. Recommend optimizing for peak hours based on observed traffic patterns.",
            "structured_data": [
                { "label": "Segment A", "value": 45 },
                { "label": "Segment B", "value": 32 },
                { "label": "Segment C", "value": 18 },
                { "label": "Segment D", "value": 25 },
                { "label": "Segment E", "value": 40 }
            ],
            "python_code": "# Mock analysis code\nimport pandas as pd\ndf = pd.DataFrame(data)\nprint(df.describe())",
            "notebook_cells": [
                { "type": "markdown", "content": "# Data Analysis Report\nGenerated by AI Data Agent." },
                { "type": "code", "content": "import pandas as pd\nimport matplotlib.pyplot as plt\n# Mock analysis plot..." }
            ]
        }

    prompt = f"""
    CSV Metadata: {json.dumps(metadata)}
    User Goal: {user_prompt}
    
    Please provide the analysis in the requested JSON format.
    """
    
    response = model.generate_content(
        contents=[SYSTEM_PROMPT, prompt],
        generation_config={"response_mime_type": "application/json"}
    )
    
    return json.loads(response.text)
